name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.json'
      - 'package.json'
      - 'package-lock.json'
      - '.node-version'
      - 'vite.config.ts'
      - 'vite.storybook.config.ts'
      - '.storybook/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [main]
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.json'
      - 'package.json'
      - 'package-lock.json'
      - '.node-version'
      - 'vite.config.ts'
      - 'vite.storybook.config.ts'
      - '.storybook/**'
      - '.github/workflows/ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # cromaticでコケないように完全な履歴を取得
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm ci
          npx playwright install

      - name: Run Vitest
        run: npm run test
      - name: Run TypeScript check
        run: npm run typecheck
      - name: Run Biome check
        run: npm run lint
      - name: Build
        run: npm run build

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
          onlyChanged: true # TurboSnap enable
        env:
          VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
